---
#- stat: path=/home/hanstra
#  register: homedirs

- name: Make sure hanstra is a user on the box
  user:
    name: hanstra
    uid: 34606
    groups: users
    comment: "Tom Hanstra"
    createhome: yes
    shell: /bin/bash
    password: '$6$vKc8QWycwQFO/IP8$Yri3turaxAl7LADUvytP3DpDOs05xp7enzp5.iGJ.AiHyxarAckQnbAEcLspIuWb/AdWEfkIearbNiNPleas/1'

- name: Make directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: ~hanstra/.ssh, mode: '0700' }
    - { path: ~hanstra/bin, mode: '0755' }
    - { path: ~hanstra/.aws, mode: '0755' }

- name: Set ownership 
  file:
    path: ~hanstra
    owner: hanstra
    group: users
    mode: 0755
    recurse: yes
    
- name: Copy files 
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: home/.aliasb, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.bash_functions, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.bash_profile, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.bashrc, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_common_b, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_oracle_sid_b, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_path_b, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.set_prompt_b, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/bin/taws, dest: ~hanstra/bin, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/bin/taws_test, dest: ~hanstra/bin, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/bin/psgrep, dest: ~hanstra/bin, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/bin/tarcp, dest: ~hanstra/bin, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/bin/set_prompt, dest: ~hanstra/bin, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.aws/config, dest: ~hanstra/.aws, owner: 'hanstra', group: 'users', mode: '0700' }
    - { file: home/.aws/credentials, dest: ~hanstra/.aws, owner: 'hanstra', group: 'users', mode: '0700' }
    - { file: home/.ssh/authorized_keys, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0700' }
    - { file: home/.ssh/config, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0644' }
    - { file: home/.ssh/id_rsa.pub, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0644' }
    - { file: home/.ssh/id_rsa, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0600' }
    - { file: home/.ssh/id_ed25519.pub, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0644' }
    - { file: home/.ssh/id_ed25519, dest: ~hanstra/.ssh, owner: 'hanstra', group: 'users', mode: '0600' }
    - { file: sudo_hanstra, dest: /etc/sudoers.d, owner: 'root', group: 'root', mode: '0400' }
 
- name: Copy csh files if shell is set
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: home/.aliasc, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.cshrc, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_common_c, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_oracle_sid_c, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.make_path_c, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
    - { file: home/.set_prompt_c, dest: ~hanstra, owner: 'hanstra', group: 'users', mode: '0755' }
  when: shell is defined

- name: Add alias to root .bashrc
  lineinfile: >
    dest=/root/.bashrc
    line="alias tah='source ~hanstra/.bashrc'"
    state=present
 
- name: Add alias to root .bashrc
  lineinfile: >
    dest=/home/ec2-user/.bashrc
    line="alias tah='source ~hanstra/.bash_profile'"
    state=present
