---
#- name: Perform some command on the remote server
#  shell: /bin/df | sort > /tmp/{{ host }}.out

#- name: Perform some command on the remote server
#  shell: ps -ef | grep awslogs > /tmp/{{ host }}.out

#- name: Perform some command on the remote server
#  shell: uname -a > /tmp/{{ host }}.out

- name: Copy the local crontab entries
  shell: cat /var/spool/cron/* > /tmp/{{ host }}.out

- name: Allow list to be copied
  file:
    path: /tmp/{{ host }}.out
    mode: '0777'
  ignore_errors: true

- name: Copy the files to global storage
  shell: scp /tmp/{{ host }}.out hanstra@john.lc.nd.edu:/global/sysadmin/compare/cmd_output
  become: true
  become_user: hanstra
  ignore_errors: true

#  shell: scp /tmp/{{ host }}.out hanstra@john.lc.nd.edu:/global/sysadmin/compare/cmd_output
