---
ansible_ssh_host: 129.74.223.226
ansible_host: aleph23-prep.library.nd.edu
host: aleph23-prep.library.nd.edu
lchost: aleph23-prep.lc.nd.edu
tagName: aleph23-prep
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 aleph23-prep server'
tagEnvironment: prep
tagOwner: hanstra
tagService: "aleph23-prep"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.1.166"
shell: /bin/tcsh
# Disk 2 parameters
rebuild_disk: true
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: exlibris }
partition:
 - { FSType: ext4, DeviceName: /dev/sdb1, MountPoint: /exlibris }
...
