ansible_ssh_host: 172.22.10.16
host: annex-prod.library.nd.edu
ssh_host: annex-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-04681a1dbd79675a5
subnet_id: subnet-84c977f3
instance_type: t3.medium
tagName: libnd-annex-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "production server - Annex update 2018"
tagEnvironment: production
tagOwner: hanstra
tagService: "annex-ims"
tagSchedule: '*'
tagBackup: True
#  sg-bcf985d8 = libnd-ssh-nd       sg-bf10f9db = libnd_annex (sgp-libnd-sysadmin)
#  sg-8dba44f6 = libnd-just-aws
security_groups: 'sg-bcf985d8,sg-bf10f9db,sg-8dba44f6'
# Application parameters
passenger_version: 5.3.4
passenger_root: /usr/local/share/gems/gems/passenger-5.3.4
passenger_ruby: /usr/bin/ruby
# Database info
annex_pg_server: libnd-aurora-pg.lc.nd.edu
annex_pg_db: annex_prod
annex_pg_user: annex_prod_dba
nginx_root: /home/app/annex-ims/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: production
second_volume: False
solr_install_version: 7.4.0
solr_port: 8080
solr_core: annex-ims
repo_solr_config: /home/app/annex-ims/current/solr_conf
rails_log_file: /home/app/annex-ims/shared/log/prod.log
sneakers_log_file: /home/app/annex-ims/shared/log/sneakers.log
tomcat_log_file: /var/log/tomcat8/catalina.out
