ansible_ssh_host: 172.22.9.42
host: annex-ims-prod.library.nd.edu
lchost: annex-ims-prod.lc.nd.edu
ssh_host: annex-ims-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: annex-ims-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "production server - Annex 2021 build"
tagEnvironment: production
tagOwner: hanstra
tagService: "annex-ims"
tagSchedule: "*"
tagBackup: True
# Application parameters
passenger_version: 6.0.8
passenger_root: /usr/local/share/gems/gems/passenger-6.0.8
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/annex-ims/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: production
second_volume: False
solr_install_version: 8.7.0
solr_port: 8080
solr_core: annex-ims
repo_solr_config: /home/app/annex-ims/current/solr_conf
rails_log_file: /home/app/annex-ims/shared/log/production.log
sneakers_log_file: /home/app/annex-ims/shared/log/sneakers.log
