ansible_ssh_host: 172.22.10.29
host: api-prod.library.nd.edu
ssh_host: api-prod.lc.nd.edu
lchost: api-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-01e3b8c3a51e88954
subnet_id: subnet-84c977f3
instance_type: t3.medium
#elastic_IP_alloc: eipalloc-0e5a6776b4f08444c
tagName: libnd-api-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Production server - API server - AWS"
tagEnvironment: production
tagOwner: hanstra
tagService: "api"
tagSchedule: "*"
tagBackup: True
#  sg-0157f302f7a058ba4 = peered-api-SG
#  sg-03a3bdb188f5174a4 = peered-mysql-prod access
security_groups: "sg-0157f302f7a058ba4,sg-03a3bdb188f5174a4"
api_gateway: '172.22.10.81:/libnd-nfs-api'
# Application parameters
passenger_version: 5.3.4
passenger_root: /usr/local/share/gems/gems/passenger-5.3.4
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/api/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: production
second_volume: False
solr_install_version: 7.4.0
solr_port: 8080
solr_core: api
repo_solr_config: /home/app/api/current/solr_conf
rails_log_file: /home/app/api/shared/log/production.log
sneakers_log_file: /home/app/api/shared/log/sneakers.log
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'api-prod'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
