ansible_ssh_host: 172.22.9.22
host: archivesspace351-test.library.nd.edu
ssh_host: archivesspace351-test.libnd.nd.edu
lchost: archivesspace351-test.libnd.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: archivesspace351-test
tagContact: lib-esu-group@nd.edu
tagDescription: "test server - ArchivesSpace - V3.5.1"
tagEnvironment: test351
tagOwner: hanstra
tagService: "archivesspace"
tagSchedule: "Mon *-18,Tue *-18,Wed *-18,Thu *-18,Fri *-18"
#tagSchedule: "*"
tagBackup: True
tagProject: "ArchivesSpace"
ansible_python_interpreter: python3
gwTimeZone: "Eastern"
app_full_access: True
Region: 'us-east-1'
lwagent_log:
  - /esu/cwagent-config/archivesspace-pui
# Application parameters
as_version: "v3.5.1"
as_upgrade: false
connector_version: "8.3.0"
solr_install_version: "8.11.4"
solr_port: "8090"
solr_core: "archivesspace"
repo_solr_config: "/home/app/archivesspace/solr"
# Test SAML
as_saml_metadata_url: "https://okta.nd.edu/app/exkp9fty480gaeuxt357/sso/saml/metadata"
as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exkp9fty480gaeuxt357/sso/saml"
# Prep SAML
#as_saml_metadata_url: "https://okta.nd.edu/app/exke61f0q0zo6NUMQ357/sso/saml/metadata"
#as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exke61f0q0zo6NUMQ357/sso/saml"
# Prod SAML
#as_saml_metadata_url: "https://okta.nd.edu/app/exk7uriv9xArfrW8f357/sso/saml/metadata"
#as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exk7uriv9xArfrW8f357/sso/saml"
#
# ArchivesSpace access URLs
public_host: archivesspace351-test.libnd.nd.edu
public_host_alias: archivesspace-test.library.nd.edu
staff_host: archivesspace351-test.libnd.nd.edu
staff_host_alias: archivesspace-staff-test.library.nd.edu
oai_host: archivesspace351-test.libnd.nd.edu
oai_host_alias: archivesspace-oai-test.library.nd.edu
api_host: archivesspace351-test.libnd.nd.edu
api_host_alias: archivesspace-api-test.library.nd.edu
stop_logrotate: false
# Plugin parameters
aspace_search_modifications_install: true
Oauth_install: true 
aeon_fulfillment_install: true
bulk_updater_install: true 
bulk_updater_version: "1.5.5"
bulk_updater_upgrade: true  
digitization_work_order_install: true  
digitization_work_order_version: "1.13"
digitization_work_order_upgrade: true  
export_service_install: false 
lcnaf_install: true
# Requests info
requests_email_address: "pmilhoan@nd.edu"
requests_fallback_email_address: "fboze@nd.edu"
# Alarm parameters
ami_id: true
alarm_hostname: 'archivesspace-test'
cpu_threshold: 98
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
namespace: "EC2-Linux"
