ansible_ssh_host: 172.22.9.25
host: archivesspace34i-prep.library.nd.edu
ssh_host: archivesspace34i-prep.libnd.nd.edu
lchost: archivesspace34i-prep.libnd.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: archivesspace34i-prep
tagContact: lib-esu-group@nd.edu
tagDescription: "prep server - ArchivesSpace - V3.4.0"
tagEnvironment: prep34
tagOwner: hanstra
tagService: "archivesspace"
#tagSchedule: "Mon *-18,Tue *-18,Wed *-18,Thu *-18,Fri *-18"
tagSchedule: "*"
tagBackup: True
tagProject: "ArchivesSpace"
ansible_python_interpreter: python3
gwTimeZone: "Eastern"
app_full_access: True
Region: 'us-east-1'
# Application parameters
as_version: "v3.4.0-RC1"
as_upgrade: false
connector_version: "8.0.30"
solr_install_version: "8.11.2"
#solr_install_version: "9.2.1"
solr_port: "8090"
solr_core: "archivesspace"
repo_solr_config: "/home/app/archivesspace/solr"
as_saml_metadata_url: "https://okta.nd.edu/app/exke61f0q0zo6NUMQ357/sso/saml/metadata"
as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exke61f0q0zo6NUMQ357/sso/saml"
public_host: archivesspace34i-prep.libnd.nd.edu
public_host_alias: archivesspace34i-prep.library.nd.edu
staff_host: archivesspace34i-prep.libnd.nd.edu
staff_host_alias: archivesspace34i-staff-prep.library.nd.edu
oai_host: archivesspace34i-prep.libnd.nd.edu
oai_host_alias: archivesspace34i-oai-prep.library.nd.edu
api_host: archivesspace34i-prep.libnd.nd.edu
api_host_alias: archivesspace34i-api-prep.library.nd.edu
external_solr: true
stop_logrotate: true
# Plugin parameters
digitization_work_order_version: "1.13"
digitization_work_order_upgrade: "true"
bulk_updater_version: "1.5.2"
bulk_updater_upgrade: "true"
# Requests info
requests_email_address: "pmilhoan@nd.edu"
requests_fallback_email_address: "fboze@nd.edu"
