ansible_ssh_host: 172.22.9.23
host: archivesspace351-prod.library.nd.edu
ssh_host: archivesspace351-prod.libnd.nd.edu
lchost: archivesspace351-prod.libnd.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: archivesspace351-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "prod server - ArchivesSpace - V3.5.1"
tagEnvironment: prod351
tagOwner: hanstra
tagService: "archivesspace"
#tagSchedule: "Mon *-18,Tue *-18,Wed *-18,Thu *-18,Fri *-18"
tagSchedule: "*"
tagBackup: True
tagProject: "ArchivesSpace"
ansible_python_interpreter: python3
gwTimeZone: "Eastern"
app_full_access: True
Region: 'us-east-1'
lwagent_log:
  - /esu/cwagent-config/archivesspace-pui
# Application parameters
as_version: "v3.5.1"
as_upgrade: false
connector_version: "8.3.0"
solr_install_version: "8.11.3"
solr_port: "8090"
solr_core: "archivesspace"
repo_solr_config: "/home/app/archivesspace/solr"
# Archivesspace35 SAML
#as_saml_metadata_url: "https://okta.nd.edu/app/exkp9fty480gaeuxt357/sso/saml/metadata"
#as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exkp9fty480gaeuxt357/sso/saml"
# Prep SAML
#as_saml_metadata_url: "https://okta.nd.edu/app/exke61f0q0zo6NUMQ357/sso/saml/metadata"
#as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exke61f0q0zo6NUMQ357/sso/saml"
# Prod SAML
as_saml_metadata_url: "https://okta.nd.edu/app/exk7uriv9xArfrW8f357/sso/saml/metadata"
as_saml_idp_sso_target_url: "https://okta.nd.edu/app/nd_archivespacenew_1/exk7uriv9xArfrW8f357/sso/saml"
#
# ArchivesSpace access URLs 
#public_host: archivesspace351-prod.libnd.nd.edu
#public_host_alias: archivesspace35.library.nd.edu
#staff_host: archivesspace351-prod.libnd.nd.edu
#staff_host_alias: archivesspace35-staff.library.nd.edu
#oai_host: archivesspace351-prod.libnd.nd.edu
#oai_host_alias: archivesspace35-oai.library.nd.edu
#api_host: archivesspace.351-prodlibnd.nd.edu
#api_host_alias: archivesspace35-api.library.nd.edu
public_host: archivesspace351-prod.libnd.nd.edu
public_host_alias: archivesspace.library.nd.edu
staff_host: archivesspace351-prod.libnd.nd.edu
staff_host_alias: archivesspace-staff.library.nd.edu
oai_host: archivesspace351-prod.libnd.nd.edu
oai_host_alias: archivesspace-oai.library.nd.edu
api_host: archivesspace351-prod.libnd.nd.edu
api_host_alias: archivesspace-api.library.nd.edu
stop_logrotate: false
# Plugin parameters
Oauth_install: true 
aspace_search_modifications_install: true 
bulk_updater_install: true 
bulk_updater_version: 1.5.5
bulk_updater_upgrade: true 
digitization_work_order_install: true 
digitization_work_order_version: 1.13
digitization_work_order_upgrade: true 
export_service_install: false
lcnaf_install: true 
# Requests info
requests_email_address: "pmilhoan@nd.edu"
requests_fallback_email_address: "fboze@nd.edu"
# Alarm parameters
ami_id: true
alarm_hostname: 'archivesspace351-prod'
cpu_threshold: 98
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
namespace: "EC2-Linux"
