ansible_ssh_host: 172.22.10.33
host: clavius-prod.library.nd.edu
ssh_host: clavius-prod.lc.nd.edu
lchost: clavius-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-062f7200baf2fa504
subnet_id: subnet-84c977f3
instance_type: t3a.micro
volumesize: 20
device_name: '/dev/xvda'
IAMProfile: 'iam-BasicInstanceProfile-1WT0D3FLL2TQV'
#elastic_IP_alloc: eipalloc-0c6dcecd0783022f7
tagName: clavius-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "Production server - Clavius"
tagEnvironment: production
tagOwner: hanstra
tagService: "clavius"
tagSchedule: '*'
tagBackup: True
#  sg-00dacc773e95a6b1d	- Clavius access security group
#  sg-03a3bdb188f5174a4 - peered-mysql-prod-Connect
security_groups: 'sg-00dacc773e95a6b1d,sg-03a3bdb188f5174a4'
# Application parameters
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
apache_user: app
apache_group: app
ServerAlias: clavius.library.nd.edu
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Disk 2 parameters
# Set to true during initial build or repartitioning
SecondaryVolume: "vol-0177166118d5b4b3b"
rebuild_disk: false
volume_device: "/dev/xvdb"
volume_group: clavius
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Clavius }
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /home/app/clavius }
Region: 'us-east-1'
alarm_hostname: 'clavius-prod'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
  - { name: "app",
      fstype: "ext4",
      device: "nvme1n1p1",
      path:   "/home/app/clavius"}
...
