---
ansible_ssh_host: 172.22.9.99
host: coral-prod.library.nd.edu
ssh_host: coral-prod.lc.nd.edu
lchost: coral-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-0d75792cec3bb5c2b
subnet_id: subnet-ac5aa187
instance_type: t3a.micro
elastic_IP_alloc: eipalloc-dc2bfaa5
IAMProfile: 'iam-BasicInstanceProfile-1WT0D3FLL2TQV'
tagName: libnd-coral-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Production server - Coral - AWS"
tagEnvironment: production
tagOwner: hanstra
tagService: "coral"
tagSchedule: "*"
tagBackup: True
#  sg-0751cf6750dce9bc4	- peered-coral-sg - CF based SG created for Coral
#  sg-03a3bdb188f5174a4 - peered-mysql-prod-Connect
security_groups: 'sg-0751cf6750dce9bc4, sg-03a3bdb188f5174a4'
# Application parameters
db_server : peered-mysql-prod.lc.nd.edu
db_user: coral_prod_dba
ServerRoot: /etc/httpd
ServerAlias: coral.library.nd.edu
ServerAdmin: hanstra@nd.edu
DocumentRoot: /home/app/coral
apache_user: app
apache_group: app
httpd_port:
  - { port: 80 }
  - { port: 443 }
...
