---
ansible_ssh_host: 10.71.1.122
ansible_host: curate-test3.library.nd.edu
host: curate-test3.library.nd.edu
lchost: curate-test3.lc.nd.edu
tagName: curate-test3
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 curate-test3 server'
tagEnvironment: test
tagOwner: hanstra
tagService: "curate-test3"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.1.122"
mysql_server: 'mysql-prep.lc.nd.edu'
app_full_access: True
app_db_password: "{{ lookup('aws_ssm', '/all/mysqlserver/prep/app', decrypt=True ) }}"
bendo_db_user: 'bendo_staging_dba'
bendo_db_password: "{{ lookup('aws_ssm', '/all/mysqlserver/prep/bendo_staging_dba', decrypt=True ) }}"
bendo_db_name: 'bendo_test3_staging'
curate_db_user: 'curate_staging_dba'
curate_db_password: "{{ lookup('aws_ssm', '/all/curatend/staging/database/database_password', decrypt=True ) }}"
curate_db_name: 'curate_test3_staging'
fedora3_db_user: 'fedora3_staging_dba'
fedora3_db_password: "{{ lookup('aws_ssm', '/all/fedora3/staging/database_password', decrypt=True ) }}"
fedora3_db_name: 'fedora3_test3_staging'
smb_mountpoint: /mnt/curatend-batch
smb_server: //library.corpfs.nd.edu/DCNS/Library/Departmental/curatend-batch
# Variables for VLAN1036 connection and mount
vlan1036_interface: ens256
vlan1036_ip: 192.168.49.24
dternity_mountpoint: /mnt/bendo
dternity_server: dternity-vlan1036
dternity_oit_mountpoint: /shares/library_CurateND_staging
...
