---
ansible_ssh_host: 10.71.1.51
ansible_host: curatesvr-prod.library.nd.edu
host: curatesvr-prod.library.nd.edu
lchost: curatesvr-prod.lc.nd.edu
tagName: curatesvr-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 curatesvr-prod server'
tagEnvironment: production
tagOwner: hanstra
tagService: "curatesvr-prod"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.1.51"
app_full_access: True
lwagent_log:
  - /esu/cwagent-config/curate-r7-nginx
# Collectd parameters
collectd_process: True
collectd_process_checks:
 - { process: "nginx" }
 - { process: "runsv" }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'curatesvr-prod'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
process_checks:
  - { name: "nginx",
    comparison: "LessThanThreshold",
    threshold: 1,
    instance: 'nginx'}
  - { name: "unicorn_disadis",
    comparison: "LessThanThreshold",
    threshold: 2,
    instance: 'runsv'}
...
