---
ansible_ssh_host: 10.71.1.140
ansible_host: curate-test2.library.nd.edu
host: curate-test2.library.nd.edu
lchost: curate-test2.lc.nd.edu
tagName: curate-test2
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 curate-test2 server'
tagEnvironment: test
tagOwner: hanstra
tagService: "curate-test2"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.1.140"
mysql_server: 'mysql-prep.lc.nd.edu'
app_full_access: True
app_db_password: "{{ lookup('aws_ssm', '/all/mysqlserver/prep/app', decrypt=True ) }}"
bendo_db_user: 'bendo_staging_dba'
bendo_db_password: "{{ lookup('aws_ssm', '/all/mysqlserver/prep/bendo_staging_dba', decrypt=True ) }}"
bendo_db_name: 'bendo_test2_staging'
curate_db_user: 'curate_staging_dba'
curate_db_password: "{{ lookup('aws_ssm', '/all/curatend/staging/database/database_password', decrypt=True ) }}"
curate_db_name: 'curate_test2_staging'
fedora3_db_user: 'fedora3_staging_dba'
fedora3_db_password: "{{ lookup('aws_ssm', '/all/fedora3/staging/database_password', decrypt=True ) }}"
fedora3_db_name: 'fedora3_test2_staging'
smb_mountpoint: /mnt/curatend-batch
smb_server: //library.corpfs.nd.edu/DCNS/Library/Departmental/curatend-batch
...
