---
ansible_ssh_host: 10.71.1.49
ansible_host: curatewkr-prod.library.nd.edu
host: curatewkr-prod.library.nd.edu
lchost: curatewkr-prod.lc.nd.edu
tagName: curatewkr-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 curatewkr-prod server'
tagEnvironment: production
tagOwner: hanstra
tagService: "curatewkr-prod"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.1.49"
app_full_access: True
smb_mountpoint: /mnt/curatend-batch
smb_server: //library.corpfs.nd.edu/DCNS/Library/Departmental/curatend-batch
# Collectd parameters
collectd_process: True
collectd_process_checks:
 - { process: "svlogd" }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'curatewkr-prod'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "dm-0",
      path:   "/"}
process_checks:
  - { name: "batchs_resque",
    comparison: "LessThanThreshold",
    threshold: 2,
    instance: 'svlogd'}
...
