---
ansible_ssh_host: 10.71.0.240
ansible_host: cw-monitor-vmw.library.nd.edu
host: cw-monitor-vmw.library.nd.edu
lchost: cw-monitor-vmw.lc.nd.edu
tagName: cw-monitor-vmw
tagContact: lib-esu-group@nd.edu
tagDescription: 'RHEL7 cw-monitor-vmw server'
tagEnvironment: production
tagOwner: hanstra
tagService: "cw-monitor-vmw"
http_notify_groups: admins
lc_interface: "ens224"
lc_ip: "10.71.0.240"
app_full_access: False
# Collectd parameters
collectd_web: True
collectd_web_checks:
 - { website: "main_website",
     url: "https://library.nd.edu/" }
 - { website: "annex-prod",
     url: "https://annex.library.nd.edu/" }
 - { website: "api-prod",
     url: "https://api.library.nd.edu/" }
 - { website: "clavius-prod",
     url: "https://clavius.library.nd.edu/" }
 - { website: "concordance-prod",
     url: "https://concordance.library.nd.edu/" }
 - { website: "coral-prod",
     url: "https://coral.library.nd.edu/" }
 - { website: "dave-prod",
     url: "https://dave.library.nd.edu/" }
 - { website: "factotum-prod",
     url: "https://factotum.library.nd.edu/" }
 - { website: "freshwriting-prod",
     url: "https://freshwriting.nd.edu/" }
 - { website: "inquisition-prod",
     url: "https://inquisition.library.nd.edu/" }
 - { website: "apache-prod",
     url: "https://cds.library.nd.edu/" }
 - { website: "datamart-prod",
     url: "https://datamart.library.nd.edu/" }
 - { website: "events-prod",
     url: "https://hackathon.library.nd.edu/" }
 - { website: "rabbitmq-prod",
     url: "http://libnd-rabbitmq-prod.lc.nd.edu:15672" }
 - { website: "london-prod",
     url: "https://london.library.nd.edu/" }
 - { website: "medieval-micro-prod",
     url: "https://medieval-microfilms-and-facsimiles.library.nd.edu/" }
 - { website: "noids-r7-prod",
     url: "http://noids.lc.nd.edu:13001/pools" }
 - { website: "rarebooks-prod",
     url: "https://rarebooks.library.nd.edu/" }
 - { website: "repository-prod",
     url: "https://repository.library.nd.edu/view/29" }
 - { website: "reserves-prod",
     url: "https://reserves.library.nd.edu/" }
 - { website: "rome-prod",
     url: "https://rome.library.nd.edu/" }
 - { website: "scsearch-prod",
     url: "https://speccol.library.nd.edu/collections/newspapers/www/amer_brit_search.html" }
 - { website: "sipity-prod",
     url: "https://deposit.library.nd.edu/areas/etd" }
 - { website: "tantur-prod",
     url: "https://tantur.library.nd.edu/" }
 - { website: "aleph23-prod",
     url: "https://alephprod.library.nd.edu/" }
 - { website: "ezproxy-prod",
     url: "https://login.proxy.library.nd.edu/" }
 - { website: "fedora38-prod",
     url: "https://fedoraprod.library.nd.edu:8443/fedora/describe" }
 - { website: "bendo-prod",
     url: "http://bendo-prod-vm.library.nd.edu:14000/item/9g54xg97d8g" }
 - { website: "curate-prod",
     url: "https://curate.nd.edu/" }
 - { website: "curate-download",
     url: "https://curate.nd.edu/downloads/vh53ws88w1m" }
 - { website: "curate-oai",
     url: "https://curate.nd.edu/oai?verb=Identify" }
 - { website: "hesarchive-prod",
     url: "https://hesburghportal.nd.edu/" }
 - { website: "honeycomb-prod",
     url: "https://collections.library.nd.edu/" }
 - { website: "honeypot-prod",
     url: "https://honeypot.library.nd.edu/images/honeycomb/000/002/000/002/medium/fighting_words-title_graphic-v3b.jpg" }
 - { website: "seaside-prod",
     url: "https://seaside.library.nd.edu/" }
 - { website: "curatesolr-prod",
     url: "https://curatesolr-prod.lc.nd.edu:8443/solr/#/" }
 - { website: "seaside-fedora",
     url: "https://fedoraprod.library.nd.edu:8443/fedora/get/ARCH-SEASIDE:1910/thumbnail" }
collectd_ping: True
collectd_host_checks:
  - "lib-hpv01.vm.nd.edu"
  - "lib-hpv02.vm.nd.edu"
  - "lib-hpv03.vm.nd.edu"
  - "lib-hpv04.vm.nd.edu"
  - "lib-hpv06.vm.nd.edu"
  - "lib-hpv07.vm.nd.edu"
  - "lib-hpv09.vm.nd.edu"
  - "lib-hpv10.vm.nd.edu"
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'cw-monitor-vmw'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
...
