---
#ansible_python_interpreter: /usr/bin/python
ansible_ssh_host: 172.22.9.50
host: cw-monitor.library.nd.edu
lchost: cw-monitor.lc.nd.edu
Region: 'us-east-1'
tagName: cw-monitor
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS Cloudwatch Webmonitor'
tagEnvironment: prep
tagOwner: hanstra
tagService: "Webmonitor"
tagBackup: True
AMI: "unknown"
collectd_web: True
collectd_web_checks: 
 - { website: "main_website",
     url: "https://library.nd.edu/" }
 - { website: "annex-prod",
     url: "https://annex-ims.library.nd.edu/" }
 - { website: "apache-prod",
     url: "https://cds.library.nd.edu/" }
 - { website: "api-prod",
     url: "https://api.library.nd.edu/" }
 - { website: "clavius-prod",
     url: "https://clavius.library.nd.edu/" }
 - { website: "concordance-prod",
     url: "https://concordance.library.nd.edu/" }
 - { website: "coral",
     url: "https://notredame.coral.bywatersolutions.com/" }
 - { website: "datamart-prod",
     url: "https://datamart.library.nd.edu/" }
 - { website: "dave-prod",
     url: "https://dave.library.nd.edu/" }
 - { website: "digital-exhibits",
     url: "https://digital-exhibits.library.nd.edu/" }
 - { website: "events-prod",
     url: "https://hackathon.library.nd.edu/" }
 - { website: "factotum-prod",
     url: "https://factotum.library.nd.edu/" }
 - { website: "freshwriting-prod",
     url: "https://freshwriting.nd.edu/" }
 - { website: "hesburgh-portal",
     url: "https://hesburghportal.nd.edu/" }
 - { website: "honeycomb",
     url: "https://honeycomb.library.nd.edu/" }
 - { website: "honeypot",
     url: "https://honeypot.library.nd.edu/images/honeycomb/000/002/000/002/medium/fighting_words-title_graphic-v3b.jpg" }
 - { website: "inquisition-prod",
     url: "https://inquisition.library.nd.edu/collections/RBSC-INQ:COLLECTION" }
 - { website: "london-prod",
     url: "https://london.library.nd.edu/" }
 - { website: "marble",
     url: "https://marble.nd.edu/" }
 - { website: "medieval-micro-prod",
     url: "https://medieval-microfilms-and-facsimiles.library.nd.edu/" }
 - { website: "noids-r7-prod",
     url: "http://noids.lc.nd.edu:13001/pools" }
 - { website: "rabbitmq-prod",
     url: "http://libnd-rabbitmq-prod.lc.nd.edu:15672" }
 - { website: "rarebooks-prod",
     url: "https://rarebooks.library.nd.edu/" }
 - { website: "repository-prod",
     url: "https://repository.library.nd.edu/view/29" }
 - { website: "reserves-prod",
     url: "https://reserves.library.nd.edu/" }
 - { website: "rome-prod",
     url: "https://rome.library.nd.edu/" }
 - { website: "scsearch-prod",
     url: "https://speccol.library.nd.edu/collections/newspapers/www/amer_brit_search.html" }
 - { website: "sipity-prod",
     url: "https://deposit.library.nd.edu/areas/etd" }
 - { website: "tantur-prod",
     url: "https://tantur.library.nd.edu/" }
 - { website: "aleph23-prod",
     url: "https://alephprod.library.nd.edu/" }
 - { website: "ezproxy-prod",
     url: "https://login.proxy.library.nd.edu/" }
 - { website: "fedora38-prod",
     url: "https://fedoraprod.library.nd.edu:8443/fedora/describe" }
 - { website: "bendo-prod",
     url: "http://bendo-prod-vm.library.nd.edu:14000/item/9g54xg97d8g" }
 - { website: "curate-prod",
     url: "https://curate.nd.edu/" }
 - { website: "curate-download",
     url: "https://curate.nd.edu/downloads/vh53ws88w1m" }
 - { website: "curate-oai",
     url: "https://curate.nd.edu/oai?verb=Identify" }
 - { website: "seaside-prod",
     url: "https://seaside.library.nd.edu/" }
 - { website: "seaside-fedora",
     url: "https://fedoraprod.library.nd.edu:8443/fedora/get/ARCH-SEASIDE:1910/thumbnail" }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'cw-monitor'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
namespace: "EC2-Linux"
...
