ansible_ssh_host: 172.22.10.29
host: datamart-prep.library.nd.edu
ssh_host: datamart-prep.libnd.nd.edu
lchost: datamart-prep.libnd.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-00068cd7555f543d5
subnet_id: subnet-84c977f3
instance_type: t3a.small
elastic_IP_alloc: eipalloc-05e70fbc9f78b507d
tagName: datamart-prep
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Prep server - Datamart - AWS 2023"
tagEnvironment: prep
tagOwner: hanstra
tagService: "libnd-datamart"
tagSchedule: "Mon *-18,Tue *-18,Wed *-18,Thu *-18,Fri *-18"
tagBackup: True
#  sg-0d0deeeb457b8c1d8 - 
security_groups: 'sg-088a1b9d4918effb3'
# Application parameters
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ServerAlias: "datamart-prep.library.nd.edu"
DocumentRoot: /shared/datamart/data/datamart
httpd_port:
  - { port: 80 }
  - { port: 443 }
apache_user: app
apache_group: app
git_branch: master
suffix: front
# Set to true when building an empty database
#build_db: false
#SecondaryVolume: ''
#rebuild_disk: false
#disk:
# - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Datamart }
#partition:
# - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /dat2 }
lwagent_log:
  - /esu/cwagent-config/datamart_access
