---
ansible_ssh_host: 129.74.223.77
host: datamart-prod.library.nd.edu
lchost: datamart-prod.lc.nd.edu
tagName: datamart-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "datamart Production server - RHEL8 - Rebuild 08/23"
tagEnvironment: production
tagOwner: hanstra
tagService: datamart
lib_interface: ens192
lib_ip: 129.74.223.77
lib_gateway: 129.74.223.1
lc_interface: ens224
lc_ip: 10.71.0.177
build_db: false
# Application parameters
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ServerAlias: "datamart.library.nd.edu"
DocumentRoot: /shared/datamart/data/datamart
httpd_port:
  - { port: 80 }
  - { port: 443 }
apache_user: app
apache_group: app
git_branch: master
suffix: build
# Disk 2 parameters
SecondaryVolume: /dev/sdb
rebuild_disk: true
collectd_file: True
collectd_file_checks:
 - { directory: "/dat2",
     instance: "order_id",
     filename: "ordr_id.dat",
     mtime: "-25h" }
collectd_process: True
collectd_process_checks:
 - { process: "httpd" }
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: datamart }
partition:
 - { FSType: xfs, DeviceName: /dev/sdb1, MountPoint: /dat2 }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'datamart-prod'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
  - { name: "dat2",
      fstype: "xfs",
      device: "sdb1",
      path:   "/dat2"}
file_checks:
  - { name: "night_build",
      comparison: "LessThanThreshold",
      threshold: 1,
      instance: 'order_id'}
process_checks:
  - { name: "httpd",
      comparison: "LessThanThreshold",
      threshold: 5,
      instance: 'httpd'}
...
