---
ansible_ssh_host: 172.22.9.139
host: datamart-prod.library.nd.edu
tagName: datamart-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "AWS Datamart - FrontEnd only"
tagEnvironment: production
tagOwner: hanstra
tagService: "datamart"
tagSchedule: '*'
tagBackup: True
ami_id: ami-06b05548a2ef9ba9e
http_notify_groups: admins,WSE
# sg-58b1023c = libnd-web-all     sg-bcf985d8 = libnd-ssh-nd
# sg-8dba44f6 = libnd-just-aws    sg-e7f74a9f = libnd-nagios
# sg-027b3366 = libnd-mysql-nd
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-8dba44f6,sg-e7f74a9f,sg-027b3366'
subnet_id: subnet-ac5aa187
instance_type: t2.medium
...
