---
ansible_ssh_host: 129.74.223.76
host: datamart-prep.library.nd.edu
lchost: datamart-prep.lc.nd.edu
tagName: datamart-prep
tagContact: lib-esu-group@nd.edu
tagDescription: "datamart prep server - RHEL8 - Rebuild 08/23"
tagEnvironment: prep
tagOwner: hanstra
tagService: datamart
lib_interface: ens192
lib_ip: 129.74.223.76
lib_gateway: 129.74.223.1
lc_interface: ens224
lc_ip: 10.71.0.180
build_db: false
# Application parameters
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ServerAlias: "datamart-prep.library.nd.edu"
DocumentRoot: /shared/datamart/data/datamart
httpd_port:
  - { port: 80 }
  - { port: 443 }
apache_user: app
apache_group: app
git_branch: master
suffix: build
# Disk 2 parameters
SecondaryVolume: /dev/sdb
rebuild_disk: true
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: datamart }
partition:
 - { FSType: xfs, DeviceName: /dev/sdb1, MountPoint: /dat2 }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'datamart-prep'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
  - { name: "dat2",
      fstype: "xfs",
      device: "sdb1",
      path:   "/dat2"}
...
