ansible_ssh_host: 172.22.9.201
host: drawings.library.nd.edu
ssh_host: drawings.lc.nd.edu
tagName: libnd-drawings
tagContact: lib-esu-group@nd.edu
tagDescription: "AWS\ Architecture\ Drawings\ server"
tagEnvironment: production
tagOwner: hanstra
tagService: "drawings"
tagBackup: True
solr_tarball: arch_draw_solr.tgz
passenger_root: /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.28
passenger_ruby: /usr/bin/ruby2.0
nginx_root: /home/app/drawings/current/public
http_notify_groups: admins,WSE
