ansible_ssh_host: 172.22.8.248
host: errbit.library.nd.edu
tagName: libnd-errbit
tagContact: lib-esu-group@nd.edu
tagDescription: "AWS\ Errbit\ server"
tagEnvironment: production
tagOwner: hanstra
tagService: "AWS\ Errbit"
tagBackup: True
http_notify_groups: admins
