---
ansible_ssh_host: 172.22.10.46
host: factotum-prod.library.nd.edu
ssh_host: factotum-prod.lc.nd.edu
lchost: factotum-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-0b69ea66ff7391e80
subnet_id: subnet-84c977f3
instance_type: t3a.micro
elastic_IP_alloc: eipalloc-0e8d8accb36dbeae9
tagName: factotum-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Production server - Factotum - AWS2"
tagEnvironment: production
tagOwner: hanstra
tagService: "factotum"
tagSchedule: '*'
tagBackup: True
#  sg-0e581dd523bb8ab04 - peered-mysql-prod-Connect
#  sg-0760b80f2151c16ca	- peered-factotum-sg
security_groups: 'sg-03a3bdb188f5174a4,sg-0760b80f2151c16ca	'
# Application parameters
#bundler_version: 1.17.3
passenger_version: 5.3.7
passenger_root: /usr/local/share/gems/gems/passenger-5.3.7
passenger_ruby: /usr/bin/ruby
ssl_certificate: library_nd_edu.chain.nginx.cer
ssl_key: library_nd_edu.key
nginx_root: /home/app/factotum/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: production
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'factotum-prod'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
...
