ansible_ssh_host: 172.22.10.44
host: factotum-prep.library.nd.edu
ssh_host: factotum-prep.lc.nd.edu
lchost: factotum-prep.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-0b69ea66ff7391e80
subnet_id: subnet-84c977f3
instance_type: t3a.micro
elastic_IP_alloc: eipalloc-08aef3dd80552f968
tagName: factotum-prep
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "prep server - Factotum - AWS2"
tagEnvironment: prep
tagOwner: hanstra
tagService: "factotum"
tagSchedule: Mon 8-18,Tue 8-18,Wed 8-18,Thu 8-18,Fri 8-18
tagBackup: True
#  sg-08ee427e6099723eb - peered-mysql-prep-serverless-Connect
#  sg-0760b80f2151c16ca	- peered-factotum-sg
security_groups: 'sg-08ee427e6099723eb,sg-0760b80f2151c16ca	'
# Application parameters
#bundler_version: 1.17.3
passenger_version: 5.3.7
passenger_root: /usr/local/share/gems/gems/passenger-5.3.7
passenger_ruby: /usr/bin/ruby
ssl_certificate: library_nd_edu.chain.nginx.cer
ssl_key: library_nd_edu.key
nginx_root: /home/app/factotum/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: prep
