---
ansible_ssh_host: 129.74.250.75
host: fedora38-prod.library.nd.edu
tagName: fedora38-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'Fedora 3.8 server'
tagEnvironment: production
tagOwner: hanstra
tagService: "fedora3"
http_notify_groups: admins,DLT
# Disk 2 parameters
rebuild_disk: true
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: Fedora}
partition:
 - { FSType: ext4, DeviceName: /dev/sdb1, MountPoint: /repo_data/fedora }
...
