---
ansible_ssh_host: 172.22.10.15
ami_id: ami-04681a1dbd79675a5
subnet_id: subnet-84c977f3
instance_type: t3.large
host: libnd-fedora3-prod.library.nd.edu
tagName: libnd-fedora3-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS Fedora 3 server - AWS Linux 2 kernel'
tagEnvironment: production
tagOwner: hanstra
tagService: "fedora3-prod"
tagSchedule: '*'
tagBackup: True
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-8dba44f6,sg-0ae7466e'
# Disk 2 parameters
rebuild_disk: false
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Fedora}
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /repo_data/fedora }
...
