ansible_ssh_host: 172.22.10.10
host: freshwriting-prep.library.nd.edu
lchost: freshwriting-prep.lc.nd.edu
ssh_host: freshwriting-prep.lc.nd.edu
ansible_ssh_user: ec2-user
host_alias: freshwriting-prep.library.nd.edu
# Build and tag parameters
ami_id: ami-0b898040803850657
subnet_id: subnet-84c977f3
instance_type: t3a.medium
elastic_IP_alloc: eipalloc-0f0bcf75db37ddee8
tagName: freshwriting-prep
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Freshwriting service - Prep"
tagEnvironment: prep
tagOwner: hanstra
tagService: "freshwriting"
tagSchedule: Mon 8-18,Tue 8-18,Wed 8-18,Thu 8-18,Fri 8-18
tagBackup: True
#  sg-044b69e3d8b3c9941 - peered-freshwriting-sg 
#  sg-08ee427e6099723eb - peered-mysql-prep-serverless-Connect
security_groups: 'sg-044b69e3d8b3c9941, sg-08ee427e6099723eb'
# Add the Secondary disk for shared data - Need VolumeID of disk
SecondaryVolume: vol-0863a1e7f4548bbe8
volume_device: /dev/sdb
# Set to true during initial build or repartitioning; then change to false to mount already created disk
rebuild_disk: false
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: Freshwriting }
partition:
 - { FSType: ext4, DeviceName: /dev/sdb1, MountPoint: /home/app/freshwriting/shared }
# Application parameters
freshwriting_branch: "master"
fwdbserver: peered-mysql-prep-serverless.cluster-cyjao3pjfcvf.us-east-1.rds.amazonaws.com
#fwdbserver: peered-mysql-prep-serverless.lc.nd.edu
fwdb: freshwriting_prep
fwdbuser: freshwriting_prep_dba
fwdb_pass_ps: /all/freshwriting/prep/database_password
fw_secret_key_ps: /all/freshwriting/prep/devise_secrets
passenger_version: 5.3.4
passenger_root: /usr/local/share/gems/gems/passenger-5.3.4
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/freshwriting/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
ssl_certificate: library_nd_edu.chain.nginx.cer
ssl_key: library_nd_edu.key
Rails_ENV: prep
second_volume: False
solr_install_version: 7.7.1
solr_port: 8080
solr_core: freshwriting
repo_solr_config: /home/app/freshwriting/current/solr_conf
rails_log_file: /home/app/freshwriting/shared/log/prep.log
sneakers_log_file: /home/app/freshwriting/shared/log/sneakers.log
