ansible_ssh_host: 172.22.10.11
host: freshwriting-prod.library.nd.edu
lchost: freshwriting-prod.lc.nd.edu
ssh_host: freshwriting-prod.lc.nd.edu
ansible_ssh_user: ec2-user
host_alias: freshwriting.nd.edu
# Build and tag parameters
ami_id: ami-0b898040803850657
subnet_id: subnet-84c977f3
instance_type: t3a.medium
#elastic_IP_alloc: eipalloc-0f0bcf75db37ddee8
tagName: freshwriting-prod
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Freshwriting server - production"
tagEnvironment: production
tagOwner: hanstra
tagService: "freshwriting"
tagSchedule: '*'
tagBackup: True
#  sg-044b69e3d8b3c9941 - peered-freshwriting-sg 
#  sg-03a3bdb188f5174a4 - peered-mysql-prod-Connect
security_groups: 'sg-044b69e3d8b3c9941, sg-03a3bdb188f5174a4'
# Add the Secondary disk for shared data - Need VolumeID of disk
SecondaryVolume: vol-0201322187fbc5133
volume_device: /dev/sdb
# Set to true during initial build or repartitioning; then change to false to mount already created disk
rebuild_disk: true
disk:
 - { BlockDevice: /dev/sdb, PartitionNumber: 1, name: Freshwriting }
partition:
 - { FSType: ext4, DeviceName: /dev/sdb1, MountPoint: /home/app/freshwriting/shared }
# Application parameters
freshwriting_branch: "master"
fwdbserver: peered-mysql-prod.lc.nd.edu
fwdb: freshwriting_prod
fwdbuser: freshwriting_prod_dba
fwdb_pass_ps: /all/freshwriting/production/database_password
fw_secret_key_ps: /all/freshwriting/production/devise_secrets
passenger_version: 5.3.4
passenger_root: /usr/local/share/gems/gems/passenger-5.3.4
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/freshwriting/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
ssl_certificate: freshwriting_nd_edu_combined.cer
ssl_key: freshwriting.nd.edu.key
Rails_ENV: production
second_volume: False
solr_install_version: 7.7.2
solr_port: 8080
solr_core: freshwriting
repo_solr_config: /home/app/freshwriting/current/solr_conf
rails_log_file: /home/app/freshwriting/shared/log/production.log
sneakers_log_file: /home/app/freshwriting/shared/log/sneakers.log
