ansible_ssh_host: 172.22.10.10
host: fw-prep.library.nd.edu
lchost: fw-prep.lc.nd.edu
ssh_host: fw-prep.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-0c6b1d09930fac512
subnet_id: subnet-84c977f3
instance_type: t3a.micro
elastic_IP_alloc: eipalloc-0f0bcf75db37ddee8
tagName: libnd-fw-prep
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "Freshwriting service - Prep"
tagEnvironment: prep
tagOwner: hanstra
tagService: "Freshwriting"
tagSchedule: Mon 8-18,Tue 8-18,Wed 8-18,Thu 8-18,Fri 8-18
tagBackup: True
#  sg-044b69e3d8b3c9941 - peered-fw-sg - CF based SG created for API
#  sg-0e581dd523bb8ab04 - peered-mysql-prep-Connect
security_groups: 'sg-044b69e3d8b3c9941, sg-0e581dd523bb8ab04'
# Application parameters
passenger_version: 5.3.4
passenger_root: /usr/local/share/gems/gems/passenger-5.3.4
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/fw/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: prep
second_volume: False
solr_install_version: 7.7.1
solr_port: 8080
solr_core: fw
repo_solr_config: /home/app/fw/current/solr_conf
rails_log_file: /home/app/fw/shared/log/prep.log
sneakers_log_file: /home/app/fw/shared/log/sneakers.log
