ansible_ssh_host: 129.74.250.120
host: honeypotprod.library.nd.edu
tagName: honeypotprod
tagEnvironment: production
config_file: honeypotprod.conf
config_dest: /etc/httpd/conf.d/ssl.conf
config_owner: app
config_group: app
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'honeypotprod.library.nd.edu'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "ext4",
      device: "mapper/vg_dbpprd2-lv_root",
      path:   "/"}
  - { name: "honeypot",
      fstype: "ext4",
      device: "sdb1",
      path:   "/mnt/vol_honeypot"}
