---
ansible_ssh_host: 172.22.10.23
host: libnd-apache-prep.library.nd.edu
tagName: libnd-apache-prep
# Apache variables - Server
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Apache variables: websites
apache_user: app
apache_group: app
websites:
  - { site_name: 'innovation-prep', site_alias: 'innovation-prep', site_root: 'innovation-prep', repository: 'website-innovation', ssl_file: ssl_wildcard.conf}
...
