---
ansible_ssh_host: 129.74.250.241
ansible_host: james.library.nd.edu
lchost: james.library.nd.edu
host: james.library.nd.edu
tagName: james
tagContact: lib-esu-group@nd.edu
tagDescription: 'Storage server'
tagEnvironment: production
tagOwner: hanstra
tagService: 'Storage'
volume_device: '/dev/sdb1'
volume_group: 'james_big_vg'
lvol: 
  - { volumename : black_pearl, volumesize: '2000g', mountpoint: /bp_tmp }
  - { volumename : gdrive, volumesize: '2000g', mountpoint: /gdrive }
  - { volumename : global_bkup, volumesize: '1000g', mountpoint: /global_bkup }
  - { volumename : history, volumesize: '3000g', mountpoint: /history }
  - { volumename : a23-prep-tmp, volumesize: '500g', mountpoint: /aleph23-prep-tmp}
  - { volumename : a23-prod-tmp, volumesize: '500g', mountpoint: /aleph23-prod-tmp}
  - { volumename : oracle_00, volumesize: '800g', mountpoint: /ora_ora00}
  - { volumename : oracle_logs, volumesize: '4000g', mountpoint: /oracle_logs}
  - { volumename : old_global, volumesize: '800g', mountpoint: /old_global }
  - { volumename : syslog, volumesize: '1000g', mountpoint: /logs }
#  - { volumename : backup, volumesize: '100g', mountpoint: /backup }
#  - { volumename : oracle_01, volumesize: '800g', mountpoint: /ora_ora01}
#  - { volumename : oracle_02, volumesize: '800g', mountpoint: /ora_ora02}
#  - { volumename : oracle_03, volumesize: '800g', mountpoint: /ora_ora03}
#nagios_checks:
# - { nagios_check_command: "backup_error",
#     nagios_check_name: "check_backup_error",
#     nagios_plugin_command: "check_file.pl -n /opt/borg-backup-scripts/config/backup_data_error" }
rh_packages:
     - authconfig
     - bind-utils
     - bzip2
     - curl
     - diffutils
     - finger
     - gcc
     - gd
     - gd-devel
     - git
     - httpd
     - libcmpiCppImpl0
     - libpng-devel
     - lsof
     - ltrace
     - man
     - mailx
     - mysql
     - mysql-devel
     - net-tools
     - net-snmp-utils
     - ntp
     - openssh-clients
     - openwsman-client
     - openwsman-server
     - parted
     - perl
     - perl-devel
     - postgresql-devel
     - sblim-sfcb
     - sblim-sfcc
     - strace
     - tcpdump
     - tmux
     - unzip
     - wget
     - yum-utils
     - zip
sudousers:
 - thanstra
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'james'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
  - { name: "a23-prep",
      fstype: "ext4",
      device: "mapper/james_big_vg-a23--prep--tmp",
      path:   "/aleph23-prep-tmp"}
...
