# This is going to an unpeered network so cannot ssh to private IP. Set to go to public
# ansible_ssh_host filled in after build completed
ansible_ssh_host: 18.236.141.56
private_host: 10.0.3.25
ami_id: ami-01bbe152bf19d0289
subnet_id: subnet-02135025212cc7326
security_groups: sg-0b08b8768b869482c
instance_type: t3.micro
host: jumpbox-prep.library.nd.edu
tagName: testlibnd-jumpbox-prep
tagContact: lib-esu-group@nd.edu
tagDescription: "Jumpbox"
tagEnvironment: prep
tagOwner: hanstra
tagService: "jumpbox"
tagSchedule: "*"
tagBackup: True
httpd_template: jumpbox
httpd_root: /home/app/jumpbox
