---
ansible_ssh_host: 172.22.10.23
ami_id: ami-0922553b7b0369273
subnet_id: subnet-84c977f3
#elastic_IP_id: eni-09b738a7f48606547
elastic_IP_alloc: eipalloc-075687b76d33a95bc
host: libnd-apache-prep.library.nd.edu
lchost: apache-prep.lc.nd.edu
tagName: libnd-apache-prep
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS Apache server - AWS Linux 2 kernel'
tagEnvironment: prep
tagOwner: hanstra
tagService: "apache-prep"
tagBackup: True
# Set the SecondaryDisk after volume build.
SecondaryVolume: vol-0e5a1f489ca912071
# Peered-websites - sg-0d14f476ba399d668
security_groups: 'sg-0d14f476ba399d668'
volume_device: "/dev/sdb"
volume_group: websites 
#Apache variables - base
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ETD_alias: etd-prep.library.nd.edu
apache_user: app
apache_group: app
smb_gateway: '//172.22.10.81/libnd-smb/www'
smb_mountpoint: '/mnt/corpfs_web'
creds_user: '!lib-libguest'
# Disk 2 parameters
# Set to true during initial build or repartitioning
rebuild_disk: true
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Websites }
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /vol2 }
...
