---
ansible_ssh_host: 172.22.10.23
ami_id: ami-0922553b7b0369273
subnet_id: subnet-84c977f3
#elastic_IP_id: eni-09b738a7f48606547
elastic_IP_alloc: eipalloc-075687b76d33a95bc
host: libnd-apache-prep.library.nd.edu
tagName: libnd-apache-prep
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS Apache server - AWS Linux 2 kernel'
tagEnvironment: prep
tagOwner: hanstra
tagService: "apache-prep"
tagBackup: True
# Set the SecondaryDisk after vol-rbsc-prep volume build.
SecondaryVolume: vol-0c72457f0f2160289
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-8dba44f6'
volume_device: "/dev/sdb"
volume_group: websites 
#Apache variables - base
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ETD_alias: etd-prep.library.nd.edu
apache_user: app
apache_group: app
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Disk 2 parameters
# Set to true during initial build or repartitioning
rebuild_disk: true
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Websites }
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /home/app }
...
