ansible_ssh_host: 172.22.9.52
host: freshwriting-prep.library.nd.edu
tagName: libnd-freshwriting-prep
tagContact: lib-esu-group@nd.edu
tagDescription: "AWS\ FreshWriting\ server\ -\ prep"
tagEnvironment: prep
tagOwner: hanstra
tagService: "freshwriting"
tagBackup: True
rails_env: pre_production
solr_install_version: 6.6.2
solr_port: 8080
solr_tarball: fw_solr.tgz
solr_core: freshwriting
repo_solr_config: /home/app/freshwriting/current/solr/configsets/freshwriting/conf
passenger_root: /usr/local/share/ruby/gems/2.1/gems/passenger-5.0.28
passenger_ruby: /usr/bin/ruby2.1
nginx_root: /home/app/freshwriting/current/public
ssl_certificate: /etc/ssl/wildcard.library.nd.edu.crt_chain.crt
ssl_certificate_key: /etc/ssl/wildcard.library.nd.edu.key
http_notify_groups: admins,WSE
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-e7f74a9f,sg-8dba44f6'
appuser: thanstra
