---
ansible_ssh_host: 172.22.10.24
ami_id: ami-0922553b7b0369273
subnet_id: subnet-84c977f3
#elastic_IP_id: eni-008ed084f28dd5a3e
host: libnd-apache-prod.library.nd.edu
tagName: libnd-apache-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS Apache server - production'
tagEnvironment: production
tagOwner: hanstra
tagService: "apache-server"
tagBackup: True
SecondaryVolume: vol-0ad6ea482d844da3b
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-8dba44f6,sg-e7f74a9f'
volume_device: "/dev/sdb"
volume_group: websites 
#Apache variables - base
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
ETD_alias: etd-prod.library.nd.edu
apache_user: app
apache_group: app
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Disk 2 parameters
# Set to true during initial build or repartitioning
rebuild_disk: true
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Websites }
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /home/app }
...
