ansible_ssh_host: 172.22.9.108
host: london-prod-2020.library.nd.edu
admin_host: london-admin-prod-2020.library.nd.edu
lchost: london-prod-2020.lc.nd.edu
host_alias : london.library.nd.edu
admin_host_alias: london-admin.library.nd.edu
# Build and tag parameters
subnet_id: subnet-ac5aa187
ami_id: ami-02a3e0c2da41029b8
instance_type: t3a.medium
#elastic_IP_alloc: 
IAMProfile: 'iam-BasicInstanceProfile-1WT0D3FLL2TQV'
volumesize: 10
device_name: /dev/sda1
tagName: london-prod-2020
tagContact: lib-esu-group@nd.edu
tagDescription: "London\ Koha\ server\ -\ prod"
tagEnvironment: production
tagOwner: hanstra
tagService: "London\ Koha\ V19.11"
tagSchedule: '*'
tagBackup: True
# sg-0465873f4611619ea	- CF Security Group for Koha
# sg-08d7b6c2c1d102aad  - CF Security Group for GG MySQL access
security_groups: sg-0465873f4611619ea,sg-08d7b6c2c1d102aad
# Koha variables
kohadb: london_prod
kohadbserver: peered-gg-mysql-prod.lc.nd.edu
kohadbuser: london_prod_dba
kohadb_pass_ps: /all/koha-london/prod/database_password
kohaadminlogin_ps: /all/koha/all/kohaadminlogin
webserver_domain: 'library.nd.edu'
gwTimeZone: "Europe/London"
zone_changed: True
koha_notices: True
zebra_full_hour: 17
yaz_version: "5.28.0"
zebra_version: "2.1.4"
full_index: daily
koha_version: "19.11.04"
http_notify_groups: admins
en_lang: True
new_install: False
# shibboleth entries
EntityID: "https://koha.library.nd.edu/shibboleth"
SSOEntityID: "http://www.okta.com/exk11bbdt3CuaDOPb357"
OITOktaURL: "https://okta.nd.edu/app/exk11bbdt3CuaDOPb357/sso/saml/metadata"
shibboleth_keys:
  - { localfile: "sp-signing-key.pem", remote_file: "sp-signing-key.pem",  mode: 600 }
  - { localfile: "sp-signing-cert.pem", remote_file: "sp-signing-cert.pem",  mode: 644 }
  - { localfile: "sp-encrypt-key.pem", remote_file: "sp-encrypt-key.pem",  mode: 600 }
  - { localfile: "sp-encrypt-cert.pem", remote_file: "sp-encrypt-cert.pem", mode: 644 }
