ansible_ssh_host: 172.22.9.113
host: london-prod.library.nd.edu
admin_host: london-admin-prod.library.nd.edu
lchost: london-prod.lc.nd.edu
host_alias : london.library.nd.edu
admin_host_alias: london-admin.library.nd.edu
# Build and tag parameters
tagName: london-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "London Koha server - production"
tagEnvironment: production
tagOwner: hanstra
tagService: "London Koha V20.11"
tagSchedule: '*'
tagBackup: True
# Koha variables
kohadb: london_prod
kohadbserver: peered-koha-mysql-prod.lc.nd.edu
kohadbuser: london_prod_dba
kohadb_pass_ps: /all/koha-london/prod/database_password
kohaadminlogin_ps: /all/koha/all/kohaadminlogin
webserver_domain: 'library.nd.edu'
gwTimeZone: "Europe/London"
zone_changed: True
koha_notices: True
zebra_full_hour: 17
yaz_version: "5.30.0"
zebra_version: "2.2.2"
full_index: daily
koha_version: "20.11"
http_notify_groups: admins
en_lang: True
new_install: False
# shibboleth entries
EntityID: "https://koha.library.nd.edu/shibboleth"
SSOEntityID: "http://www.okta.com/exk11bbdt3CuaDOPb357"
OITOktaURL: "https://okta.nd.edu/app/exk11bbdt3CuaDOPb357/sso/saml/metadata"
shibboleth_keys:
  - { localfile: "sp-signing-key.pem", remote_file: "sp-signing-key.pem",  mode: 600 }
  - { localfile: "sp-signing-cert.pem", remote_file: "sp-signing-cert.pem",  mode: 644 }
  - { localfile: "sp-encrypt-key.pem", remote_file: "sp-encrypt-key.pem",  mode: 600 }
  - { localfile: "sp-encrypt-cert.pem", remote_file: "sp-encrypt-cert.pem", mode: 644 }
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'london-prod'
cpu_threshold: 70
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
