ansible_ssh_host: 172.22.9.112
host: london-prep.library.nd.edu
admin_host: london-admin-prep.library.nd.edu
lchost: london-prep.lc.nd.edu
host_alias : london-prep.library.nd.edu
admin_host_alias: london-admin-prep.library.nd.edu
# Build and tag parameters
tagName: london-prep
tagContact: lib-esu-group@nd.edu
tagDescription: "London\ Koha\ server\ -\ prep"
tagEnvironment: prep
tagOwner: hanstra
tagService: "London\ Koha\ V20.11"
tagSchedule: 'Mon 3-18,Tue 3-18,Wed 3-18,Thu 3-18,Fri 3-18'
tagBackup: True
# Koha variables
kohadb: london_prep
kohadbserver: peered-gg-mysql-serverless.lc.nd.edu
kohadbuser: london_prep_dba
kohadb_pass_ps: /all/koha-london/prep/database_password
kohaadminlogin_ps: /all/koha/all/kohaadminlogin
webserver_domain: 'library.nd.edu'
gwTimeZone: "Europe/London"
zone_changed: True
koha_notices: False
zebra_full_hour: 17
yaz_version: "5.30.0"
zebra_version: "2.2.2"
full_index: daily
koha_version: "20.11"
http_notify_groups: admins
en_lang: True
new_install: False
# shibboleth entries
EntityID: "https://koha.library.nd.edu/shibboleth"
SSOEntityID: "http://www.okta.com/exk11bbdt3CuaDOPb357"
OITOktaURL: "https://okta.nd.edu/app/exk11bbdt3CuaDOPb357/sso/saml/metadata"
shibboleth_keys:
  - { localfile: "sp-signing-key.pem", remote_file: "sp-signing-key.pem",  mode: 600 }
  - { localfile: "sp-signing-cert.pem", remote_file: "sp-signing-cert.pem",  mode: 644 }
  - { localfile: "sp-encrypt-key.pem", remote_file: "sp-encrypt-key.pem",  mode: 600 }
  - { localfile: "sp-encrypt-cert.pem", remote_file: "sp-encrypt-cert.pem", mode: 644 }
