---
ansible_ssh_host: 172.22.9.136
host: medieval-micro-prod.library.nd.edu
tagName: libnd-medieval-micro-prod
tagContact: lib-esu-group@nd.edu
tagDescription: AWS Medieval Microfilms
tagEnvironment: production
tagOwner: hanstra
tagService: "medieval-micro"
tagBackup: True
ami_id: ami-0a5a56a19f146fcc8
http_notify_groups: admins,WSE
nginx_root: /home/app/medieval_micro/current/public
security_groups: 'sg-58b1023c,sg-bcf985d8,sg-8dba44f6,sg-e7f74a9f'
subnet_id: subnet-ac5aa187
nagios_checks:
 - { nagios_check_command: "solr_core",
     nagios_check_name: "check_solr_core",
     nagios_plugin_command: "check_http -w 5 -c 10 -H localhost -p 8080 -u '/solr/medieval_micro/select?q=&rows=0&wt=json'" }
...
