ansible_ssh_host: 172.22.10.89
host: jumpbox.library.nd.edu
ssh_host: jumpbox.libnd.nd.edu
lchost: jumpbox.libnd.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: peered-jumpbox
tagContact: lib-esu-group@nd.edu
tagDescription: "Peered jumpbox server"
tagEnvironment: prod
tagOwner: hanstra
tagService: "jumpbox"
tagSchedule: '*'
tagBackup: True
tagProject: "jumpbox"
ansible_python_interpreter: python3
# Alarm parameters
ami_id: 'For_alarm_only'
Region: 'us-east-1'
alarm_hostname: 'peered-jumpbox'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
