ansible_ssh_host: 172.22.242.140
host: jumpbox-tl.library.nd.edu
ssh_host: jumpbox-tl.lc.nd.edu
lchost: jumpbox-tl.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: peered-jumpbox-tl
tagContact: lib-esu-group@nd.edu
tagDescription: "Peered jumpbox server"
tagEnvironment: prod
tagOwner: hanstra
tagService: "jumpbox"
tagSchedule: '*'
tagBackup: True
# Alarm parameters
ami_id: 'For_alarm_only'
Region: 'us-east-1'
alarm_hostname: 'peered-jumpbox-tl'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
