ansible_ssh_host: 52.45.9.18
host: peered-jumpbox-test.library.nd.edu
ssh_host: peered-jumpbox-test.library.nd.edu
lchost: jumpbox-test.libnd.nd.edu
ansible_ssh_user: hanstra
# Build and tag parameters
tagName: peered-jumpbox
tagContact: lib-esu-group@nd.edu
tagDescription: "Peered jumpbox server"
tagEnvironment: prod
tagOwner: hanstra
tagService: "jumpbox"
tagSchedule: 'Mon *-18,Tue *-18,Wed *-18,Thu *-18,Fri *-18'
tagBackup: True
ansible_python_interpreter: python3
# Alarm parameters
ami_id: 'For_alarm_only'
Region: 'us-east-1'
alarm_hostname: 'peered-jumpbox-test'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
