---
ansible_ssh_host: 129.74.223.205
ansible_host: peter.library.nd.edu
lchost: peter-2010.library.nd.edu
host: peter.library.nd.edu
tagName: peter
tagContact: lib-esu-group@nd.edu
tagDescription: 'Storage server'
tagEnvironment: production
tagOwner: hanstra
tagService: 'Storage'
volume_device: '/dev/sdb'
volume_group: 'peter_storage_vg'
lvol: 
  - { volumename : global_1, volumesize: '2000g', mountpoint: /global }
  - { volumename : history, volumesize: '4000g', mountpoint: /history }
  - { volumename : backup, volumesize: '1000g', mountpoint: /backup }
  - { volumename : aleph1_tmp, volumesize: '1000g', mountpoint: /aleph1_tmp}
  - { volumename : pg_bkup, volumesize: '500g', mountpoint: /pg_bkup}
  - { volumename : mysql_bkup, volumesize: '500g', mountpoint: /mysql_bkup}
  - { volumename : borg_bkup, volumesize: '4000g', mountpoint: /borg_bkup}
  - { volumename : borg_test, volumesize: '1000g', mountpoint: /borg_test}
nagios_checks:
 - { nagios_check_command: "backup_error",
     nagios_check_name: "check_backup_error",
     nagios_plugin_command: "check_file.pl -n /opt/borg-backup-scripts/config/backup_data_error" }
rh_packages:
     - authconfig
     - bind-utils
     - bzip2
     - curl
     - diffutils
     - finger
     - git
     - lsof
     - ltrace
     - man
     - mailx
     - net-tools
     - ntp
     - openssh-clients
     - parted
     - perl
     - strace
     - tcpdump
     - unzip
     - wget
     - yum-utils
     - zip
sudousers:
 - thanstra
...
