---
ansible_ssh_host: 129.74.223.205
ansible_host: peter.library.nd.edu
lchost: peter.library.nd.edu
host: peter.library.nd.edu
tagName: peter
tagContact: lib-esu-group@nd.edu
tagDescription: 'Storage server'
tagEnvironment: production
tagOwner: hanstra
tagService: 'Storage'
volume_device: '/dev/sdb'
volume_group: 'peter_storage_vg'
lvol: 
  - { volumename : aleph23-prod-tmp, volumesize: '1000g', mountpoint: /aleph23-prod-2020}
  - { volumename : aleph23_prod_tmp, volumesize: '1000g', mountpoint: /aleph23-prod-tmp}
  - { volumename : borg_bkup, volumesize: '4000g', mountpoint: /borg_bkup}
  - { volumename : global_1, volumesize: '2000g', mountpoint: /global }
  - { volumename : global, volumesize: '2000g', mountpoint: /global_2021 }
  - { volumename : history, volumesize: '4000g', mountpoint: /history }
  - { volumename : mysql_bkup, volumesize: '500g', mountpoint: /mysql_bkup}
  - { volumename : oracle_logs, volumesize: '6000g', mountpoint: /oracle_logs}
  - { volumename : pg_bkup, volumesize: '500g', mountpoint: /pg_bkup}

#  - { volumename : backup, volumesize: '2000g', mountpoint: /backup }
#  - { volumename : bendo_tmp, volumesize: '2000g', mountpoint: /bendo_tmp}
collectd_file: True
collectd_file_checks:
 - { directory: "/opt/borg-backup-scripts/config",
     instance: "borg_error_check",
     filename: "backup_data_error",
     mtime: "5m" }
 - { directory: "/global/data/reserves/oit_data/review",
     instance: "reserves_error_check",
     filename: "reserves_data_error",
     mtime: "5m" }
nagios_checks:
 - { nagios_check_command: "backup_error",
     nagios_check_name: "check_backup_error",
     check_period: "24x7",
     nagios_plugin_command: "check_file.pl -n /opt/borg-backup-scripts/config/backup_data_error" }
 - { nagios_check_command: "backup_error_bendo",
     nagios_check_name: "check_backup_error_bendo",
     check_period: "24x7",
     nagios_plugin_command: "check_file.pl -n /opt/borg-backup-scripts/config/bendo_data_error" }
 - { nagios_check_command: "reserves_data_error",
     nagios_check_name: "check_reserves_data_error",
     check_period: "Early Morning Check",
     nagios_plugin_command: "check_file.pl -n /global/data/reserves/oit_data/review/reserves_data_error"}
 - { nagios_check_command: "seaside_fedora",
     nagios_check_name: "check_seaside_fedora",
     check_period: "24x7",
     nagios_plugin_command: "check_http.pl -H fedoraprod.library.nd.edu -u /fedora/get/ARCH-SEASIDE:1umbnail -p 8443"}
 - { nagios_check_command: "website_up",
     nagios_check_name: "check_website_up",
     check_period: "24x7",
     nagios_plugin_command: "check_http -H library.nd.edu -u /about-us -S"}
rh_packages:
     - authconfig
     - bind-utils
     - bzip2
     - curl
     - diffutils
     - finger
     - git
     - lsof
     - ltrace
     - man
     - mailx
     - net-tools
     - ntp
     - openssh-clients
     - parted
     - perl
     - strace
     - tcpdump
     - unzip
     - wget
     - yum-utils
     - zip
sudousers:
 - thanstra
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'peter'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "mapper/rhel-root",
      path:   "/"}
  - { name: "global",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-global",
      path:   "/global"}
  - { name: "pg_bkup",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-pg_bkup",
      path:   "/pg_bkup"}
  - { name: "mysql_bkup",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-mysql_bkup",
      path:   "/mysql_bkup"}
  - { name: "borg_bkup",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-borg_bkup",
      path:   "/borg_bkup"}
  - { name: "a23-prod",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-aleph23_prod_tmp",
      path:   "/aleph23-prod-tmp"}
  - { name: "ora_log",
      fstype: "ext4",
      device: "mapper/peter_storage_vg-oracle_logs",
      path:   "/oracle_logs"}
file_checks:
  - { name: "borg-error",
      comparison: "GreaterThanThreshold",
      threshold: 0,
      instance: 'borg_error_check'}
  - { name: "reserves-error",
      comparison: "GreaterThanThreshold",
      threshold: 0,
      instance: 'reserves_error_check'}
...
