---
ansible_ssh_host: 172.22.10.26
ami_id: ami-009d6802948d06e52
subnet_id: subnet-84c977f3
#elastic_IP_alloc: eipalloc-0fbd777a2da55a9df
host: rbsc-prod.library.nd.edu
tagName: libnd-rbsc-prod
tagContact: lib-esu-group@nd.edu
tagDescription: 'AWS RBSC server - AWS Linux 2 kernel'
tagEnvironment: production
tagOwner: hanstra
tagService: "rarebooks"
tagBackup: True
# Set AvailabilityZone based upon subnet
AvailabilityZone: us-east-1d
# sg-bcf985d8 = SSH-ND      sg-8dba44f6 = Just AWS
# sg-58b1023c = Web-all     sg-e7f74a9f = nagios
security_groups: 'sg-bcf985d8,sg-8dba44f6,sg-58b1023c'
#Apache variables - base
ServerRoot: "/home/app/rarebooks"
ServerAlias: "rarebooks.library.nd.edu"
ServerAdmin: "hanstra@nd.edu"
apache_user: app
apache_group: app
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Settings for Storage Gateway
sg_netid: "!lib-libguest"
sg_password_lookup: "/all/rbsc/production/sg_password"
sg_mountpoint: "/home/app/rarebooks"
...
