ansible_ssh_host: 172.22.10.42
host: reserves-prep.library.nd.edu
ssh_host: reserves-prep.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
ami_id: ami-0c6b1d09930fac512
subnet_id: subnet-84c977f3
instance_type: t3.small
elastic_IP_alloc: eipalloc-051269970019957d3
tagName: libnd-reserves-prep
tagContact: web-and-software-engineering-group@nd.edu
tagDescription: "prep server - Reserves - AWS"
tagEnvironment: prep
tagOwner: hanstra
tagService: "reserves"
tagSchedule: Mon 8-18,Tue 8-18,Wed 8-18,Thu 8-18,Fri 8-18
tagBackup: True
#  sg-0d20080fb0ba554c7 - peered-reserves-sg - CF based SG created for Reserves
#  sg-0e581dd523bb8ab04 - peered-mysql-prep-Connect
security_groups: 'sg-0d20080fb0ba554c7, sg-0e581dd523bb8ab04'
# Application parameters
bundler_version: 1.17.3
passenger_version: 5.3.7
passenger_root: /usr/local/share/gems/gems/passenger-5.3.7
passenger_ruby: /usr/bin/ruby
nginx_root: /home/app/reserves/current/public
nginx_access_log: /opt/nginx/logs/access.log
nginx_error_log: /opt/nginx/logs/error.log
Rails_ENV: prep
rails_log_file: /home/app/reserves/shared/log/prep.log
sneakers_log_file: /home/app/reserves/shared/log/sneakers.log
# Set to true during initial build or repartitioning
volume_device: "/dev/xvdb"
volume_group: reserves
SecondaryVolume: 'vol-0168dc36250ba1330'
rebuild_disk: false
disk:
 - { BlockDevice: /dev/xvdb, PartitionNumber: 1, name: Reserves }
partition:
 - { FSType: ext4, DeviceName: /dev/xvdb1, MountPoint: /mnt/Ereserves }
