ansible_ssh_host: 172.22.9.104
host: rome-prod-2020.library.nd.edu
admin_host: rome-admin-prod-2020.library.nd.edu
lchost: rome-prod-2020.lc.nd.edu
host_alias : rome.library.nd.edu
admin_host_alias: rome-admin.library.nd.edu
# Build and tag parameters
subnet_id: subnet-ac5aa187
ami_id: ami-02a3e0c2da41029b8
instance_type: t3a.medium
#elastic_IP_alloc: 
IAMProfile: 'iam-BasicInstanceProfile-1WT0D3FLL2TQV'
volumesize: 10
device_name: /dev/sda1
tagName: rome-prod-2020
tagContact: lib-esu-group@nd.edu
tagDescription: "Rome\ Koha\ server\ -\ prod"
tagEnvironment: production
tagOwner: hanstra
tagService: "Rome\ Koha\ V19.11"
tagSchedule: '*'
tagBackup: True
# sg-0465873f4611619ea  - CF Security Group for Koha
# sg-08d7b6c2c1d102aad  - CF Security Group for GG MySQL access
security_groups: sg-0465873f4611619ea,sg-08d7b6c2c1d102aad
# Koha variables
kohadb: rome_prod_2020
kohadbuser: rome_prod_dba
kohadbserver: peered-gg-mysql-prod.lc.nd.edu
kohadb_pass_ps: /all/koha-rome/prod/database_password
kohaadminlogin_ps: /all/koha/all/kohaadminlogin
webserver_domain: 'library.nd.edu'
zebra_full_hour: 17
zone_changed: True
gwTimeZone: "Europe/Rome"
koha_notices: True
yaz_version: "5.28.0"
zebra_version: "2.1.4"
full_index: daily
koha_version: "19.11.04"
http_notify_groups: admins
en_lang: False
new_install: False
# shibboleth entries
EntityID: "https://koha.library.nd.edu/shibboleth"
SSOEntityID: "http://www.okta.com/exk11bbdt3CuaDOPb357"
OITOktaURL: "https://okta.nd.edu/app/exk11bbdt3CuaDOPb357/sso/saml/metadata"
shibboleth_keys:
  - { localfile: "sp-signing-key.pem", remote_file: "sp-signing-key.pem",  mode: 600 }
  - { localfile: "sp-signing-cert.pem", remote_file: "sp-signing-cert.pem",  mode: 644 }
  - { localfile: "sp-encrypt-key.pem", remote_file: "sp-encrypt-key.pem",  mode: 600 }
  - { localfile: "sp-encrypt-cert.pem", remote_file: "sp-encrypt-cert.pem", mode: 644 }
