ansible_ssh_host: 172.22.9.111
host: scsearch2-prod.library.nd.edu
ssh_host: scsearch2-prod.lc.nd.edu
lchost: scsearch2-prod.lc.nd.edu
ansible_ssh_user: ec2-user
# Build and tag parameters
tagName: scsearch2-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "Production server - SC Search2"
tagEnvironment: production
tagOwner: hanstra
tagService: "scsearch2"
tagSchedule: '*'
tagBackup: True
#  sg-00dacc773e95a6b1d	- Jumpbox access security group
#  sg-03a3bdb188f5174a4 - peered-mysql-prod-Connect
security_groups: 'sg-00dacc773e95a6b1d,sg-03a3bdb188f5174a4'
# Application parameters
ServerRoot: "/etc/httpd"
ServerAdmin: "hanstra@nd.edu"
apache_user: app
apache_group: app
ServerAlias: speccol.library.nd.edu
httpd_port:
  - { port: 80 }
  - { port: 443 }
# Alarm parameters
ami_id: 'For_alarm_only'
Region: 'us-east-1'
alarm_hostname: 'scsearch2-prod'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "xfs",
      device: "nvme0n1p1",
      path:   "/"}
