ansible_ssh_host: 129.74.223.164
host: seasideprod-vm.library.nd.edu
tagName: seasideprod-vm
tagEnvironment: production
config_file: seasideprod-vm.conf
config_dest: /opt/nginx/conf/nginx.conf
config_owner: app
config_group: app
# Alarm parameters
Region: 'us-east-1'
alarm_hostname: 'seasideprod-vm.library.nd.edu'
cpu_threshold: 30
disk_config:
  - { name: "root",
      fstype: "ext4",
      device: "mapper/vg_dbpprd2-lv_root",
      path:   "/"}
