ansible_ssh_host: 172.22.10.40
host: tantur-prod.library.nd.edu
admin_host: tantur-admin-prod.library.nd.edu
lchost: tantur-prod.lc.nd.edu
host_alias: tantur.library.nd.edu
admin_host_alias: tantur-admin.library.nd.edu
subnet_id: subnet-84c977f3
ami_id: ami-089ff1b061da37276
instance_type: t3a.xlarge
elastic_IP_alloc: ''
tagName: libnd-tantur-prod
tagContact: lib-esu-group@nd.edu
tagDescription: "Tantur\ Koha\ server\ -\ prod"
tagEnvironment: production
tagOwner: hanstra
tagService: "Tantur\ Koha\ V18.11"
tagSchedule: '*'
tagBackup: True
kohadb: tantur_prod
kohadbserver: peered-gg-mysql-prod.lc.nd.edu
kohadbuser: tantur_prod_dba
kohadb_pass_ps: /all/koha-tantur/prod/database_password
kohaadminlogin_ps: /all/koha/all/kohaadminlogin
zone_changed: True
gwTimeZone: "Asia/Jerusalem"
koha_notices: True
http_notify_groups: admins
yaz_version: "5.27.1"
zebra_version: "2.1.4"
full_index: weekly
koha_version: "18.11.03"
en_lang: False
# sg-0465873f4611619ea  - CF Security Group for Koha
# sg-08d7b6c2c1d102aad  - CF Security Group for GG MySQL access
security_groups: sg-0465873f4611619ea,sg-08d7b6c2c1d102aad
EntityID: "https://tantur.library.nd.edu/shibboleth"
SSOEntityID: "http://www.okta.com/exkj1z509v8BGbxFN356"
OITOktaURL: "https://dev-364467.okta.com/app/exkj1z509v8BGbxFN356/sso/saml/metadata"
shibboleth_keys:
  - { localfile: "tantur/sp-signing-key.pem", remote_file: "sp-signing-key.pem",  mode: 600 }
  - { localfile: "tantur/sp-signing-cert.pem", remote_file: "sp-signing-cert.pem",  mode: 644 }
  - { localfile: "tantur/sp-encrypt-key.pem", remote_file: "sp-encrypt-key.pem",  mode: 600 }
  - { localfile: "tantur/sp-encrypt-cert.pem", remote_file: "sp-encrypt-cert.pem", mode: 644 }
